### ISSUE TITLE
Error compiling on Alpine Linux 3.21 amd64

### ISSUE THREAD

**Issue by lpvm** [levaidaniel/kc#10]
I think that have installed the necessary dependencies.
There's this error when trying to compile on Alpine Linux 3.21, on a amd64 system.

```
$ make -f Makefile.linux 
make -C bcrypt -f Makefile.linux
make[1]: Entering directory '..../git_clones/kc/bcrypt'
cc -pedantic -Wall `pkg-config --cflags libcrypto` `pkg-config --cflags libbsd` `pkg-config --cflags libxml-2.0` -D_READLINE -D_BUNDLED_BCRYPT -D_OS_LINUX   -c -o bcrypt_pbkdf.o bcrypt_pbkdf.c
In file included from bcrypt_pbkdf.c:23:
sha2.h:63:14: error: expected ';' before 'void'
   63 | __BEGIN_DECLS
      |              ^
      |              ;
   64 | void SHA256Init(SHA2_CTX *);
      | ~~~~          
sha2.h:75:12: error: expected ';' before 'typedef'
   75 | __END_DECLS
      |            ^
      |            ;
In file included from /usr/include/bsd/sys/cdefs.h:54,
                 from /usr/include/bsd/string.h:39,
                 from bcrypt_pbkdf.c:26:
/usr/include/sys/cdefs.h:4:2: warning: #warning usage of non-standard #include <sys/cdefs.h> is deprecated [-Wcpp]
    4 | #warning usage of non-standard #include <sys/cdefs.h> is deprecated
      |  ^~~~~~~
make[1]: *** [<builtin>: bcrypt_pbkdf.o] Error 1
make[1]: Leaving directory '..../git_clones/kc/bcrypt'
make: *** [Makefile.linux:78: bcrypt] Error 2
```

**Platform**
```
$ uname -a
Linux bigram 6.12.11-0-lts #1-Alpine SMP PREEMPT_DYNAMIC 2025-01-24 20:02:52 x86_64 Linux
```
```

 $ cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.21.2
PRETTY_NAME="Alpine Linux v3.21"
```

 - Libraries/features linked and their versions [e.g. libykpers, libscrypt, pcre, openssl, etc...]
```
openssl-3.3.2-r5
libbsd-0.12.2-r0
libxml2-2.13.4-r3
```

**Comment by levaidaniel** [comment]
Alpine has musl libc that doesn't support __BEGIN_DECLS for starters. I could replace that but there are a bunch of others things that will also break down the road.
I guess the best answer here is *kc* in this shape and form doesn't support musl libc. And as far as I understood, Alpine doesn't really support glibc - or at least there are challenges involved in replacing musl.

**Comment by lpvm** [comment]
Maybe you can find the time someday to start supporting musl.
There's a lot of [Linux distros](https://wiki.musl-libc.org/projects-using-musl.html)  that use it, including Alpine and Void.
Thank you.
